version: "3.8"

services:
  userapi:
    build:
      context: .
    command: ["npm", "start"]
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - userapi-mongo

  # Database where all the users and session information will be stored.
  userapi-mongo:
    image: mongo

  mongo-expres:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_SERVER=userapi-mongo
    depends_on:
      - userapi-mongo

volumes:
  logvolume01: {}
